development:
  adapter: postgresql
  encoding: utf8
  database: <%= name %>_development
  host: localhost
  prepared_statements: false

test:
  adapter: postgresql
  encoding: utf8
  database: <%= name %>_test
  host: localhost
  prepared_statements: false

production:
  adapter: postgresql
  encoding: utf8
  database: <%= name %>_production
  host: localhost
  prepared_statements: false
